"""add table for storing current NoTD

Revision ID: 16d2665c01a2
Revises: 42bcd0b13aca
Create Date: 2025-11-24 22:21:13.653544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d2665c01a2'
down_revision: Union[str, Sequence[str], None] = '42bcd0b13aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notd',
    sa.Column('niko_id', sa.Integer(), nullable=False),
    sa.Column('chosen_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niko_id'], ['nikos.id'], ),
    sa.PrimaryKeyConstraint('niko_id')
    )
    op.create_index(op.f('ix_notd_chosen_at'), 'notd', ['chosen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notd_chosen_at'), table_name='notd')
    op.drop_table('notd')
    # ### end Alembic commands ###
