"""only one row of banner (aka. only one banner in database, at all times)

Revision ID: 343bda100616
Revises: de2ea9d113ca
Create Date: 2026-01-07 10:27:49.419557

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "343bda100616"
down_revision: Union[str, Sequence[str], None] = "de2ea9d113ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "banner", sa.Column("banner_identifier", sa.String(100), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("banner", "banner_identifier")
    # ### end Alembic commands ###
