"""added is_blacklisted

Revision ID: 3812bc432283
Revises: 65f456018507
Create Date: 2025-11-28 22:26:57.515867

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3812bc432283"
down_revision: Union[str, Sequence[str], None] = "65f456018507"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nikos", sa.Column("is_blacklisted", sa.Boolean(), nullable=False))
    op.add_column(
        "submissions", sa.Column("is_blacklisted", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nikos", "is_blacklisted")
    op.drop_column("submissions", "is_blacklisted")
    # ### end Alembic commands ###
