"""small fix on nikos and submissions models

Revision ID: 419d2d74be8c
Revises: b180967ed202
Create Date: 2025-11-16 16:33:34.616040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '419d2d74be8c'
down_revision: Union[str, Sequence[str], None] = 'b180967ed202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'nikos', 'users', ['author_id'], ['id'])
    op.add_column('submissions', sa.Column('image', sa.String(length=1023), nullable=False))
    op.drop_column('submissions', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('author', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('submissions', 'image')
    op.drop_constraint(None, 'nikos', type_='foreignkey')
    # ### end Alembic commands ###
