"""enforce cascading delete for table with ForeignKey

Revision ID: 65f456018507
Revises: 16d2665c01a2
Create Date: 2025-11-24 23:22:38.389911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f456018507'
down_revision: Union[str, Sequence[str], None] = '16d2665c01a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('abilities_ibfk_1'), 'abilities', type_='foreignkey')
    op.create_foreign_key(None, 'abilities', 'nikos', ['niko_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('nikos_ibfk_1'), 'nikos', type_='foreignkey')
    op.create_foreign_key(None, 'nikos', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notd_ibfk_1'), 'notd', type_='foreignkey')
    op.create_foreign_key(None, 'notd', 'nikos', ['niko_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('postniko_agenda_ibfk_1'), 'postniko_agenda', type_='foreignkey')
    op.drop_constraint(op.f('postniko_agenda_ibfk_2'), 'postniko_agenda', type_='foreignkey')
    op.create_foreign_key(None, 'postniko_agenda', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'postniko_agenda', 'nikos', ['niko_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('posts_ibfk_1'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('submissions_ibfk_1'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_ibfk_1'), 'submissions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_ibfk_1'), 'posts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'postniko_agenda', type_='foreignkey')
    op.drop_constraint(None, 'postniko_agenda', type_='foreignkey')
    op.create_foreign_key(op.f('postniko_agenda_ibfk_2'), 'postniko_agenda', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(op.f('postniko_agenda_ibfk_1'), 'postniko_agenda', 'nikos', ['niko_id'], ['id'])
    op.drop_constraint(None, 'notd', type_='foreignkey')
    op.create_foreign_key(op.f('notd_ibfk_1'), 'notd', 'nikos', ['niko_id'], ['id'])
    op.drop_constraint(None, 'nikos', type_='foreignkey')
    op.create_foreign_key(op.f('nikos_ibfk_1'), 'nikos', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'abilities', type_='foreignkey')
    op.create_foreign_key(op.f('abilities_ibfk_1'), 'abilities', 'nikos', ['niko_id'], ['id'])
    # ### end Alembic commands ###
