"""Added banner_color

Revision ID: 790d18e5c784
Revises: 343bda100616
Create Date: 2026-02-19 22:52:49.141691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790d18e5c784'
down_revision: Union[str, Sequence[str], None] = '343bda100616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('banner_color', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'banner_color')
    # ### end Alembic commands ###
