"""added discord user id field

Revision ID: 851037ca426b
Revises: e7c331fb8e54
Create Date: 2026-03-14 12:15:45.079570

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "851037ca426b"
down_revision: Union[str, Sequence[str], None] = "e7c331fb8e54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("discord_user_id", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "discord_user_id")
    # ### end Alembic commands ###
