"""move field to separate table

Revision ID: a570b239ef6a
Revises: 851037ca426b
Create Date: 2026-03-14 12:36:31.572156

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a570b239ef6a"
down_revision: Union[str, Sequence[str], None] = "851037ca426b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("discord_user_id", sa.String(length=255), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("ban_reason", sa.String(length=1023), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_user_id"),
    )
    op.drop_column("users", "discord_user_id")
    op.drop_column("users", "ban_reason")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("ban_reason", mysql.VARCHAR(length=1023), nullable=True)
    )
    op.add_column(
        "users", sa.Column("discord_user_id", mysql.VARCHAR(length=255), nullable=True)
    )
    op.drop_table("discord_connections")
    # ### end Alembic commands ###
