"""make user_id unique

Revision ID: a8baa0e2a627
Revises: 185d07fe145b
Create Date: 2025-09-10 21:23:59.106004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8baa0e2a627'
down_revision: Union[str, Sequence[str], None] = '185d07fe145b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'submit_users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submit_users', type_='unique')
    # ### end Alembic commands ###
