"""small revision

Revision ID: aeb5611d66da
Revises: 31b75caca6f7
Create Date: 2025-09-10 20:12:39.824788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aeb5611d66da'
down_revision: Union[str, Sequence[str], None] = '31b75caca6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('nikos', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=127),
               existing_nullable=False)
    op.alter_column('nikos', 'full_desc',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1023),
               existing_nullable=False)
    op.drop_column('nikos', 'image')
    op.alter_column('users', 'hashed_pass',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1023),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_pass',
               existing_type=sa.String(length=1023),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('nikos', sa.Column('image', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('nikos', 'full_desc',
               existing_type=sa.String(length=1023),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('nikos', 'name',
               existing_type=sa.String(length=127),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('blogs', 'content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
