"""change type for last_submit_on to integer

Revision ID: bb562358b75f
Revises: a8baa0e2a627
Create Date: 2025-09-10 21:57:32.025652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb562358b75f'
down_revision: Union[str, Sequence[str], None] = 'a8baa0e2a627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submit_users', 'last_submit_on',
               existing_type=mysql.DATETIME(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submit_users', 'last_submit_on',
               existing_type=sa.BigInteger(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
