"""add table for Banner

Revision ID: de2ea9d113ca
Revises: 32ac154e2577
Create Date: 2026-01-07 09:48:43.383360

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de2ea9d113ca"
down_revision: Union[str, Sequence[str], None] = "32ac154e2577"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column("is_dismissable", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(op.f("nikos_users_FK"), "nikos", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("nikos_users_FK"), "nikos", "users", ["author_id"], ["id"]
    )
    op.drop_table("banner")
    # ### end Alembic commands ###
