"""implement account type, removal of is_admin flags, implement ban_reason field

Revision ID: e7c331fb8e54
Revises: 790d18e5c784
Create Date: 2026-03-14 12:02:15.347790

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7c331fb8e54"
down_revision: Union[str, Sequence[str], None] = "790d18e5c784"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("nikos_users_FK"), "nikos", type_="foreignkey")
    op.add_column("users", sa.Column("account_type", sa.Integer(), nullable=True))
    op.add_column(
        "users", sa.Column("ban_reason", sa.String(length=1023), nullable=True)
    )

    op.execute("UPDATE users SET account_type = 0 WHERE is_admin = 0")
    op.execute("UPDATE users SET account_type = 1 WHERE is_admin = 1")

    op.alter_column("users", "account_type", existing_type=sa.Integer(), nullable=False)
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.execute("UPDATE users SET is_admin = 0 WHERE account_type = 0")
    op.execute("UPDATE users SET is_admin = 1 WHERE account_type = 1")
    op.alter_column(
        "users",
        "is_admin",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.drop_column("users", "ban_reason")
    op.drop_column("users", "account_type")
    op.create_foreign_key(
        op.f("nikos_users_FK"), "nikos", "users", ["author_id"], ["id"]
    )
    # ### end Alembic commands ###
