"""users and nikos with author id

Revision ID: f03420f9a920
Revises: 7645527b0efb
Create Date: 2025-11-16 13:15:26.052878

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f03420f9a920"
down_revision: Union[str, Sequence[str], None] = "7645527b0efb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nikos", sa.Column("author_id", sa.Integer(), nullable=True))

    op.create_foreign_key(
        op.f("nikos_users_FK"), "nikos", "users", ["author_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("nikos_users_FK"), "nikos", type_="foreignkey")
    op.drop_column("nikos", "author_id")
    # ### end Alembic commands ###
